// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::vector_2_type::Vector2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vector2`.
///
/// Obtain a handle from the [`Vector2TableAccess::vector_2`] method on [`super::RemoteTables`],
/// like `ctx.db.vector_2()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vector_2().on_insert(...)`.
pub struct Vector2TableHandle<'ctx> {
    imp: __sdk::TableHandle<Vector2>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vector2`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Vector2TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Vector2TableHandle`], which mediates access to the table `vector2`.
    fn vector_2(&self) -> Vector2TableHandle<'_>;
}

impl Vector2TableAccess for super::RemoteTables {
    fn vector_2(&self) -> Vector2TableHandle<'_> {
        Vector2TableHandle {
            imp: self.imp.get_table::<Vector2>("vector2"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Vector2InsertCallbackId(__sdk::CallbackId);
pub struct Vector2DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Vector2TableHandle<'ctx> {
    type Row = Vector2;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Vector2> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Vector2InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Vector2InsertCallbackId {
        Vector2InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Vector2InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Vector2DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Vector2DeleteCallbackId {
        Vector2DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Vector2DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Vector2>("vector2");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Vector2>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Vector2>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
